### PR TITLE
Revert "New master+wip"

### PR DESCRIPTION
**Pull request by litghost**
Reverts SymbiFlow/yosys#81

### CODE REVIEW

**Comment by litghost** [comment]
Restores version of master+wip with green Travis CI.

**Review by acomodi — APPROVED** [review]
@litghost All right, I will prepare a new master+wip so that Travis goes green. To do so we might have to disable one of the tests as it is related to having the RAMD32X1D disabled:

```
ERROR: Assertion failed: selection contains 0 elements instead of the asserted 8: t:RAM32X1D
```

**Comment by litghost** [comment]
> @litghost All right, I will prepare a new master+wip so that Travis goes green. To do so we might have to disable one of the tests as it is related to having the RAMD32X1D disabled:
> 
> ```
> ERROR: Assertion failed: selection contains 0 elements instead of the asserted 8: t:RAM32X1D
> ```

Ya, that's what I've been working on.  Hopefully I'll have an updated version today.

**Comment by litghost** [comment]
@acomodi I believe https://github.com/SymbiFlow/yosys/pull/87 will go green on travis.

**Pull request merged**
