### PR TITLE
Re enable ramb36e1

### PR DESCRIPTION
**Pull request by acomodi**
This PR updates master+wip to most recent master and re-enables RAMB36E1 inference.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
Too much changes for a human review. Let's wait for the CI. If the CI is green and the Symbiflow CI is green too then LGTM for me.

**Comment by acomodi** [comment]
Yep, the problem is that we didn't update yosys master+wip quite in a while.
The review request is just FYI to know what is happening.
I need also to locally run this and verify that nothing breaks in arch-defs, as I presume there is no CI that checks the integration between yosys master+wip and arch-defs

**Comment by acomodi** [comment]
@litghost Appears that the new master+wip merge, does not work with arch-defs. There have been ~1000 commits since the last master+wip update and something may introduced some regressions for us.

I am trying to get a new master+wip based on the previous master, so that we can land the linux-litex test and the fix for the brams. (or alternatively, just push on the current master+wip the re-enable of RAMB36 inference).

**Comment by litghost** [comment]
> @litghost Appears that the new master+wip merge, does not work with arch-defs. There have been ~1000 commits since the last master+wip update and something may introduced some regressions for us.
> 
> I am trying to get a new master+wip based on the previous master, so that we can land the linux-litex test and the fix for the brams. (or alternatively, just push on the current master+wip the re-enable of RAMB36 inference).

For now, let's make a small change to master+wip directly to get the linux-LiteX target merged.  After that is merged and green, the next priority to should be getting latest yosys re-integrated.

**Comment by acomodi** [comment]
Agreed, I will also open an issue to keep track of the problems that are encountered while rebasing on top of master.

**Pull request closed without merging**
